# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
body = '
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur dignissim nibh, interdum dictum massa gravida a. Duis ac mattis nisi. Pellentesque non aliquet augue. Praesent sed mauris arcu. Proin efficitur rutrum nunc vel lobortis. Aliquam tincidunt ultricies dui, in finibus ex pharetra nec. Pellentesque varius sapien ut nisl sollicitudin semper. Aenean nulla tellus, aliquet eu erat sit amet, tempor tempus orci. Aliquam pretium, mauris quis luctus condimentum, dui enim facilisis tellus, nec interdum velit felis vitae arcu. Vivamus purus risus, iaculis ac auctor ut, aliquam nec ante. Ut id velit lobortis, faucibus nulla condimentum, dignissim nibh. Suspendisse potenti. Nunc malesuada quis mi interdum porta. Mauris non ipsum et erat condimentum eleifend. Fusce a sem felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Etiam dapibus velit sapien, vitae feugiat massa auctor in. Duis condimentum tellus in neque iaculis gravida. Duis congue accumsan finibus. Maecenas a sem vitae ligula viverra mollis a quis nunc. Vivamus ante sem, feugiat nec augue ut, semper maximus augue. Etiam mollis sodales elit, quis elementum neque. Cras efficitur diam ipsum, non aliquam ante ultrices in. Praesent sapien odio, scelerisque in justo eu, vehicula faucibus enim. Morbi fringilla quis leo et faucibus.

Proin ut eros eu ligula viverra lobortis. Phasellus eget nisi sit amet justo placerat eleifend quis quis lorem. Suspendisse potenti. Praesent ultricies tortor lectus, quis feugiat velit venenatis a. Vestibulum id eros id erat mattis vehicula vel eget tortor. Fusce quis mauris in metus mattis varius quis ut mi. Praesent pretium cursus turpis, et porta dui bibendum sit amet. Suspendisse ut fringilla neque. Vestibulum vestibulum finibus tortor, non aliquam libero convallis id. Praesent a orci bibendum, congue tellus sed, vulputate neque. Nulla ultricies dictum iaculis.

Duis dictum velit sed justo consequat, et ultrices eros rhoncus. Aliquam erat volutpat. Mauris pulvinar ultricies aliquet. Quisque dictum, est in iaculis convallis, metus dolor rutrum turpis, non euismod elit lectus id massa. Vivamus vehicula consectetur diam nec lobortis. In egestas arcu rutrum faucibus condimentum. Sed scelerisque velit in est interdum pretium. Vivamus eleifend luctus molestie. Proin ornare mauris vel erat bibendum, non aliquam dolor mollis. Pellentesque eget lectus quis sapien blandit lobortis. Sed lacus quam, tempor eget diam a, varius mattis lacus.

Maecenas imperdiet felis at aliquam sollicitudin. Sed sem dolor, rutrum gravida justo a, pulvinar cursus velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut accumsan massa ante, eu volutpat justo vulputate in. Nunc dictum aliquam scelerisque. Nam sit amet arcu elementum, sodales orci at, rutrum risus. Etiam dui nulla, vestibulum tincidunt feugiat sit amet, feugiat at libero. Curabitur auctor arcu at ipsum molestie iaculis.'


User.destroy_all
User.create!(name: 'Sarah', username: Faker::Internet.unique.user_name, password: 'password', avatar: File.open('app/assets/images/eyes.jpg'))
User.create!(name: 'Britney', username: Faker::Internet.unique.user_name, password: 'password', avatar: File.open('app/assets/images/girl.jpg'))
User.create!(name: 'Leo', username: Faker::Internet.unique.user_name, password: 'password', avatar: File.open('app/assets/images/leo.jpg'))
User.create!(name: 'Sam', username: Faker::Internet.unique.user_name, password: 'password', avatar: File.open('app/assets/images/man.jpg'))
User.create!(name: 'Maybel', username: Faker::Internet.unique.user_name, password: 'password', avatar: File.open('app/assets/images/maybelline.jpg'))
User.create!(name: 'guest', username: 'guest', password: 'guestpass', avatar: File.open('app/assets/images/trump.png'))

Story.destroy_all

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'When visiting Frederik Ruysch in Amsterdam in 1697, tsar Peter the Great kissed one of the specimens from his anatomical museum, and afterwards bought the entire collection. Three hundred years later, the Dutch crown prince, Willem Alexander, when visiting St Petersburg, was withheld from seeing Ruysch’s work. Diplomats had decided the prince had to be spared the sight of the ‘macabre, deformed foetuses’ that Ruysch had preserved.

If he had heard this, Frederik Ruysch would have turned in his grave. Not that he would have been surprised to hear that his preparations had survived three centuries, for he would have expected nothing less. Nor would he have been astonished to find a prince taking an interest in his work. But he would have been dismayed to hear his specimens described as macabre, since it was precisely the beauty of his preparations that earned Ruysch long-lasting fame. For centuries, friend and foe alike have agreed that he should be credited, above all, with making anatomy an acceptable pursuit.

At the beginning of Honoré de Balzac’s novel La Peau de Chagrin, the young protagonist is wandering around Paris, planning to put an end to his life, when he decides to go into a curiosity shop. There he encounters what Balzac describes as an ‘enchanting creature’, the embalmed body of a child, which reminds him of his happy boyhood. This ‘sleeping’ child turns out to be a remnant of the collection of Frederik Ruysch, who had been dead for exactly a century when Balzac wrote the novel.
', author_id: User.all.sample.id, image: File.open('app/assets/images/story/a.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'The United States has in recent years become a stronghold for climate change skepticism, especially since the country’s declaration in 2001 that it would not participate in the Kyoto Protocol. Nevertheless, though it is a well-documented fact, it might surprise you to learn that, a far cry from the United States’ recent ambivalence with respect to the modern scientific theory of man-made climate change, the country’s founders were keen observers of climatic trends and might even be counted among the first climate change advocates.

From the start, the project to colonize North America had proceeded on the understanding that climate followed latitude; so dependent was climate on the angle of the sun to the earth’s surface, it was believed, that the word ‘climate’ was defined in terms of parallels of latitude. New England was expected to be as mild as England, and Virginia as hot as Italy and Spain. Surprised by harsh conditions in the New World, however, a great number of the early settlers did not outlast their first winter in the colonies. Many of the survivors returned to Europe, and in fact, the majority of 17th-century colonies in North America were abandoned.

A view formed in Europe that the New World was inferior to the Old. In particular, medical lore still held that climate lay behind the characteristic balance of the Hippocratic humors – it explained why Spaniards were temperamental and Englishmen reserved – and it was believed that the climate of the colonies caused physical and mental degeneration. Swedish explorer Pehr Kalm, who had travelled to North America on a mission from Carl Linnaeus, observed in his travel diary that the climate of the New World caused life – plants and animals, including humans – to possess less stamina, stature, and longevity than in Europe.
', author_id: User.all.sample.id, image: File.open('app/assets/images/story/andreas.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'In his comprehensive study, The Great Sea-Serpent: An Historical and Critical Treatise (1892), Dutch zoologist Antoon Cornelius Oudemans lists more than three hundred references to the notorious sea monster in his chronological “Literature on the Subject.” The first ten of those, 1555-1665, cites Olaus Magnus’s sea serpent: editions of Olaus’s Historia de gentibus septentrionalibus (“History of the Northern Peoples”) and natural histories of Conrad Gesner, Ulisse Aldrovandi, Edward Topsell, and John Jonston. The list establishes Olaus’s serpentine monster as the major ancestral source of sea serpent lore from the sixteenth century to widespread sightings of such creatures in Oudemans’s own time. It is the basis for illustration and discussion of the creature in marine studies and popular fantasy up to the present, five hundred years after Olaus created it.

While Oudemans cites natural histories in which copies or variations of Gesner’s famous woodcut of Olaus’s sea serpent appear, his list does not refer to the monster’s iconic source: the 1539 Carta Marina. Oudemans had not seen the map. After it went out of circulation by the 1580s, it was lost for three centuries until a copy was discovered in the Munich state library in 1886, shortly before publication of The Great Sea-Serpent. A second copy surfaced in 1962 and is now in the Uppsala University Library. The wall map, measuring about 5 feet (1.5m) wide and 4 feet (1.2m) high, was the largest, most accurate, and most detailed map of Scandinavia––or of any European region––at that time. A Catholic priest exiled with his Archbishop of Uppsala brother, Johannes, from their native Sweden after it converted to Lutheranism, Olaus began compiling the nationalistic map in Poland in 1527. Created to show the rest of Europe the rich history, culture, and natural wonders of the North prior to the Reformation, the map was printed in Venice twelve years later.

The northern seas of the marine and terrestrial map teem with fantastic sea monsters either drawn or approved by Olaus. The most dramatic of those, off the busy coast of Norway, below the dreaded Maelström, is the great serpent, coiling around a ship’s mast and lunging with bared teeth at a sailor on the deck. Like the map’s other sea beasts, the serpent is not just a cartographical decoration to fill space, as in Jonathan Swift’s “elephants in wont of towns.” It is meant to represent a real animal, one that Nordic sailors and fishermen vividly described to Olaus on his travels around Scandinavia. The Latin legend accompanying the image indicates the monster is 300 feet (91.4m) in length.
', author_id: User.all.sample.id, image: File.open('app/assets/images/story/anton.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'Conan Doyle’s Sherlock Holmes saga has enjoyed — or in some cases suffered – countless reinventions since its original publication from 1887 to 1927. The BBC’s current television version starring Benedict Cumberbatch is perhaps one of the most successful, not least as its scriptwriters combine a deep knowledge of the original with a flair for departing wittily from it: the show’s strategy of allusion, transformation, and up-to-dateness gives it both freshness and familiarity. The new series begins with ‘The Empty Hearse’, its title alluding playfully to Conan Doyle’s 1903 story ‘The Empty House’ in which Holmes returns from apparent death at the hands of Professor Moriarty in Switzerland.

Conan Doyle’s saga is particularly suited to this kind of treatment: the fan-critics who call themselves “Sherlockians” pore over the details of Dr John Watson’s narratives (known in the trade as “the Canon”), looking for clues, contradictions, and anomalies; they construct often conspiratorial alternative explanations of events, uncover Conan Doyle’s (or Watson’s) apparent errors, and cross-reference the stories with encyclopaedic scholarship. So, while Conan Doyle is often seen as a fairly transparent writer, eschewing complexity, technical innovation, and challenges to orthodox ideology in favour of elegant myth-making, the industriousness of the Sherlockians shows that the simplicity of these stories is often deceptive: in a story such as ‘The Empty House’, a great deal of important information is left unsaid or hinted at. Recovering those subtexts through careful reading and a knowledge of what else was going on at the time can help to show Holmes and his creator in a new light.
', author_id: User.all.sample.id, image: File.open('app/assets/images/story/beach.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'In Berlin, apart from his studies and bohemian indulgences, Zweig sought a more expansive freedom in literary terms, and caught the bug of translation. He began to explore further afield, even translating poets such as Keats and Yeats and producing with other translators a collection of Verlaine’s poetry to which he added a critically acclaimed introduction. But all the time he was moving closer to Belgium, drawn by the rich crop of its home grown artists and writers who seemed to integrate their works in fresh and creatively productive ways. So in the summer break of 1902, long anticipating a visit to the ‘little land between the languages’, Zweig made his move.

Verhaeren had come onto his radar while still at school, when he found a copy of the poet’s first Rubenesque collection Les Flamandes (1883) and instinctively attempted a clutch of translations. He had even written to Verhaeren in 1898 to secure permission to publish them in a journal. Now, he was determined to meet the man himself, though it was the novelist Camille Lemmonier, to whom Zweig had recently dedicated an essay, whom he first located in Brussels. Zweig had sent a postcard in rather shaky French to Verhaeren suggesting a meeting, but it was unclear when Zweig arrived in the Belgian capital if this rendezvous would come to pass. On arrival it seemed that Verhaeren was away and Zweig’s hopes were dashed, but by a fateful stroke, Lemmonier then invited him to meet the sculptor Charles van der Stappen, and Verhaeren just so happened to be in the sculptor’s studio sitting for a bust. Zweig’s memories of that first crucial encounter with the older man are pertinent.
', author_id: User.all.sample.id, image: File.open('app/assets/images/story/christian.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'In the early nineteen-eighties, for a commission about the sense of place in John Betjeman’s poetry, I worked with a photographer named James Ravilious. He lived in Devon, where he set forth every day to capture the profound countryside around him. His are the kind of photographs that Chaucer might have taken, monochrome and immortal. Distant windswept combes; gnarled trees; the square towers of village churches; beasts closer to the primitive earth than God – his work invites a leaning towards the word “timeless.” But James’s photographs are not timeless, and that was the first point of him – they are of their time and their time only; they are, indeed, what may be called, in the deepest sense, record.

Second point: to the sense of Time add sense of Place – because neither could these photographs have been taken in any other country; put the words “English” and “quintessence” together and you get the idea. This unique confluence was, I now think, genetic; James was the son of the similarly unmistakable Eric Ravilious.

Only Art controls Time. It can freeze it, pin its moment, accelerate it, ignore it, invent and re-invent it, spin it over, under, sideways, down. Consequently (imagination being truer than fact), our artists have become our best recorders of all our worlds. Time and Place are conjoined and frozen in the fullness of their reportage; we see how it was There and Then – in the house in Delft, where Vermeer’s girl reads her letter, or in the early twentieth-century Byleorussian village which Chagall showed from his most credible point of view, of the couple flying above it. The most touching are particular to their time and their place.

Eric Ravilious likewise recorded England in that watchful, changeful moment between the world wars. He served both masters – his own time, in his own England. Indeed, he confirms Englishness in Art, where the power so often comes from restraint; the real stuff is beneath the surface. Given an already substantial body of work in his thirty-nine years – hundreds of wood engravings, close to 100 water colours alongside multiple other outputs – we can only imagine what he might have gone on to produce had the gods of war not been so hungry.

Throughout, his own character emerges – composed, unhysterical, clear and unfettered. We can all quote Wordsworth’s famous definition of poetry in the Lyrical Ballads as ‘emotion recollected in tranquility’ but we overlook a more interesting note in the same Preface; ‘…The human mind is capable of being excited without the application of gross and violent stimulants; and he must have a very faint perception of its beauty and dignity who does not know this.’

In the super-perceptive Ravilious there are no “gross and violent stimulants,” and without blinking he put up a surfeit, almost, of “beauty and dignity” – and yet he never sacrificed his own stern and often lonely edge.

And he is so individual, so recognizable at first glance, so much his own man, because, though delighting in the Surrealists and the Chinese, he made his point without playing for any team. Not the Fauvists, not the Cubists nor the Dadaists nor the neo-Impressionists, he was also too subtle for the harsher, uber-Modernist school of his German contemporaries.
', author_id: User.all.sample.id, image: File.open('app/assets/images/story/joey.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'Although Charles Kenneth Scott Moncrieff’s translation of À la recherche du temps perdu is considered by many journalists and writers to be the best translation of any foreign work into the English language, his choice of Remembrance of Things Past as the general title alarmed the seriously ill Proust and misled generations of readers as to the novelist’s true intent. It wasn’t until 1992 that the title was finally changed to In Search of Lost Time. “Remembrance of Things Past” is a beautiful line from William Shakespeare’s sonnet 30, but it conveys an idea that is really the opposite of Proust’s own. When Scott Moncrieff chose this title, he did not know, of course, where Proust was going with the story and did not correctly interpret the title, which might indeed be taken to indicate a rather passive attempt by an elderly person to recollect days gone by.

Proust’s theory of memory rejects the notion that we can simply sit and quietly resurrect the past in its true vividness through what he called voluntary memory. When we attempt to do this, we find that it doesn’t work very well. We remember very little and often only in a haphazard and rather bland way. On the other hand, Proust’s title should be taken to suggest a different approach: the Narrator’s search (recherche means both search and research in French) is an active, arduous quest in which the past must be rediscovered—largely through what Proust called involuntary memory, as demonstrated in the famous madeleine scene—then analyzed and understood, and finally, if your ambition is to preserve it in writing, transposed and recreated in a book. As we will see, Proust lived long enough to see the title Remembrance of Things Past and, while he objected to it, did not take measures to change it.

A native of Scotland, Scott Moncrieff had served as a captain in the Scottish Borderers during World War I. Before reading A la recherche du temps perdu, he had already made a name for himself as the translator of major French works, such as La Chanson de Roland (The Song of Roland) and Stendhal’s two masterful novels Le Rouge et le Noir (The Red and the Black) and La Chartreuse de Parme (The Charterhouse of Parma). After the Great War Scott Moncrieff had served as secretary to Lord Northcliffe, in addition to being an editor at The London Times. In January 1920, a thirty-year-old Scott Moncrieff resigned his post at the Times in order to devote himself entirely to translating À la recherche du temps perdu.
', author_id: User.all.sample.id, image: File.open('app/assets/images/story/jonatan.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'It came in the 1869 April issue of the Quarterly Review. Writing an essay review of the tenth edition of Charles Lyell’s Principles of Geology, Wallace declared that “an Overruling Intelligence has watched over the action of those [natural] laws, so directing variations and so determining their accumulation, as finally to produce an organization sufficiently perfect to admit of, and even to aid in, the indefinite advancement of our mental and moral nature.” Darwin was appalled. Scratching an emphatic “NO!!!” in the margin of his copy of the Quarterly, he couldn’t believe that Wallace was the author. Some months later, when the full impact of Wallace’s blasphemy had settled in, he wailed, “But I groan over Man — you write like a metamorphosed (in retrograde direction) naturalist, and you the author of the best paper that ever appeared in the Anthropological Review! Eheu! Eheu! Eheu! — Your miserable friend, C. Darwin.”

Wallace was unmoved. Insisting that natural selection operated strictly by the principle of utility, he held that intellectual capacities of Homo sapiens were far too developed to be explained as adaptations to mere survival. He elaborated and expanded on this theme in Darwinism (1889). The origin of life and sentience in animals were, for Wallace, also wholly inexplicable by natural selection or by any other naturalistic means. “These three distinct stages of progress from the inorganic world of matter and motion up to man,” he insisted, “point clearly to an unseen universe — to a world of spirit, to which the world of matter is altogether subordinate.”

It has been suggested by some that Wallace’s conversion to spiritualism was behind his defection from Darwin. On July 22, 1865, Wallace attended his first séance with his sister Fanny. Like many other intellects of the Victorian era — in Britain there was physicist William Crookes, Nobel Laureate Lord Rayleigh, and Oliver Lodge , to name a few; in America there was noted psychologist/philosopher William James and Columbia University logician James Hervey Hyslop — Wallace became an ardent spiritualist. But Wallace’s spiritualism cannot simply be dismissed as the product of a “heretic personality.” While the frequent attribution of spiritualism’s popularity among leading Victorian intellects (especially scientists) to a “crisis of faith” no doubt has some truth, spiritualism was never completely refuted on its own terms. Stage conjurors (magicians) and leading opponents from the scientific community all failed to catch the age’s leading spiritualist, Daniel Douglas Home, in any overt chicanery and the “impostures” of renowned medium Leonora Piper were more suggested than proven. In the end, scientists who rejected spiritualism simply explained it away as wholly subjective. This is not to vindicate spiritualism it is merely to suggest that the movement posed a significant problem for scientists attempting to establish a meaningful discourse of objectivity and a normative basis for scientific inquiry based upon quantifiable empirical data on the one hand and those reliant upon personal testimony based upon experience and observation on the other. Seen in this light the contention over spiritualism is better viewed as an effort to negotiate precisely what counted as legitimate evidence rather than as a collection of séance addicted eccentrics who merely provide historians comic relief in the otherwise serious and steady march of scientific progress.
', author_id: User.all.sample.id, image: File.open('app/assets/images/story/landspace.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'On the morning of November 14, 1889, John Brisben Walker, the wealthy publisher of the monthly magazine The Cosmopolitan, boarded a New Jersey ferry bound for New York City. Like many other New Yorkers, he was carrying a copy of The World, the most widely read and influential newspaper of its time. A front-page story announced that Nellie Bly, The World’s star investigative reporter, was about to undertake the most sensational adventure of her career: an attempt to go around the world faster than anyone ever had before. Sixteen years earlier, in his popular novel, Jules Verne had imagined that such a trip could be accomplished in eighty days; Nellie Bly hoped to do it in seventy-five.

Immediately John Brisben Walker recognized the publicity value of such a scheme, and at once an idea suggested itself: The Cosmopolitan would sponsor its own competitor in the around-the-world race, traveling in the opposite direction. Of course, the magazine’s circumnavigator would have to leave immediately, and would have to be, like Bly, a young woman –the public, after all, would never warm to the idea of a man racing against a woman. But who should it be? Arriving at the offices of The Cosmopolitan that morning, Walker sent a message to the home of Elizabeth Bisland, the magazine’s literary editor. It was urgent, he indicated; she should come at once.

Each month for The Cosmopolitan Elizabeth Bisland wrote a review of recently published books entitled “In the Library.” She was a reader with refined tastes and wide-ranging interests; the subjects covered in her first few columns included Tolstoy’s social gospel, the fourteenth-century tales of Don Juan Manuel, the collected poems of Emma Lazarus, and a two-volume history of the Vikings by the Norwegian author Hjalmar Hjorth Boyeson. Born into a Louisiana plantation family ruined by the Civil War, Bisland had moved to New Orleans and then, a few years later, to New York, where she contributed to a variety of magazines and was regularly referred to as the most beautiful woman in metropolitan journalism.
', author_id: User.all.sample.id, image: File.open('app/assets/images/story/photo.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'It was about time. Three hundred years after his birth Denis Diderot is in line for receiving the highest honour France has to bestow on one of her own. President Francois Hollande announced his intention to have the encyclopedist’s remains transferred to the Panthéon in Paris or, as the French language so deliciously puts it, to have him pantheonisé.

The Panthéon is sacred ground in Paris—not because it was built as a place to worship the Almighty, but because the French Revolutionaries turned it into a site for the burial and commemoration of, as the façade proclaims, the grands hommes of the nation. Rising high above the Quartier Latin and illuminated at night by fiery orange lights, the building with its imposing cupola stands also as the memory of the French republic, cast in stone.

The building was constructed originally as the church of Saint Geneviève after Louis XV had sworn to honor the saint should he recover from a grave illness. Because of the exorbitant costs of financing the monarch’s will and whim, construction was finished only in 1791. Meanwhile, the Revolution swept over the country. The church was designated a mausoleum for the nation’s great men, the first of which, the count of Mirabeau, was admitted in 1791, only to be excluded three years later, when political allegiances had changed. History also is subject to changing administrations.

Since then the Panthéon has been the theatre of many ideological battles, the center of consecration of the French sense of self and its many permutations. Félix Éboué, a member of the colonial administration, became the first black Frenchman to enter into the hallowed ground, in 1949; the first woman, Marie Curie, in 1995. The tomb listing reads like the greatest hits of French intellectual history—Alexandre Dumas, Victor Hugo, André Maulraux, Émile Zola. The most famous philosophers interred in the crypt are two stars of Enlightenment thought: Voltaire and Jean-Jacques Rousseau, who were thus honored already during the eighteenth century—despite the fact that the former spent his adult life in exile and the latter was not even French. Tourists often pose for photographs in front of their sarcophagi.
', author_id: User.all.sample.id, image: File.open('app/assets/images/story/ryan.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'Today when someone points a camera at us, we smile. This is the cultural and social reflex of our time, and such are our expectations of a picture portrait. But in the long history of portraiture the open smile has been largely, as it were, frowned upon.

A walk around any art gallery will reveal that the image of the open smile has, for a very long time, been deeply unfashionable. Miss La Creevy’s equivocal ‘smirks’ do however make more frequent appearances: a smirk may offer artists an opportunity for ambiguity that the open smile cannot. Such a subtle and complex facial expression may convey almost anything — piqued interest, condescension, flirtation, wistfulness, boredom, discomfort, contentment, or mild embarrassment. This equivocation allows the artist to offer us a lasting emotional engagement with the image. An open smile, however, is unequivocal, a signal moment of unselfconsciousness.

Such is the field upon which the mouth in portraiture has been debated: an ongoing conflict between the serious and the smirk. The most famous and enduring portrait in the world functions around this very conflict. Millions of words have been devoted to the Mona Lisa and her smirk – more generously known as her ‘enigmatic smile’ — and so today it’s difficult to write about her without sensing that you’re at the back of a very long and noisy queue that stretches all the way back to 16th century Florence. But to write about the smile in portraiture without mentioning her is perverse, for the effect of the Mona Lisa has always been in its inherent ability to demand further examination. Leonardo impels us to do this using a combination of skilful sfumato (the effect of blurriness, or smokiness) and his profound understanding of human desire. It is a kind of magic: when you first glimpse her, she appears to be issuing a wanton invitation, so alive is the smile. But when you look again, and the sfumato clears in focus, she seems to have changed her mind about you. This is interactive stuff, and paradoxical: the effect of the painting only occurs in dialogue, yet she is only really there when you’re not really looking. The Mona Lisa is thus, in many ways, designed to frustrate — and frustrate she did.
', author_id: User.all.sample.id, image: File.open('app/assets/images/story/samuele.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'Hahnemann was in many ways a product of this ferment: while translating a medical text that mentioned cinchona bark, a New World plant used to treat malaria, he decided to resolve his doubts about its effectiveness by testing the substance on himself. He observed that cinchona produced effects on his healthy body that mimicked the effects of malaria on a sick body, leading him to theorize that successful remedies worked by treating like with like, fighting disease symptoms with substances that produce those same symptoms in the healthy. Hahnemann’s theory, which he termed “homeopathy,” directly contradicted the accepted model of treating a symptom with drugs that had opposite effects. The medical establishment immediately went on the attack, but the controversy itself attracted interest from practitioners discontented with the current rather violent state of therapeutics.

In 1811, Hahnemann returned to Leipzig to teach his new system of medicine. In order to apply the theory of treating like with like, he had to determine the homeopathic properties of every drug in the standard pharmacopeia. The scale of this project was immense: healthy volunteers would have to sample thousands of substances at varying concentrations over the course of many weeks.

Standardized research subjects did not exist, nor would the concept have served any function in the discourse of early-nineteenth century medicine; even mainstream physicians understood therapeutics to be highly individualized, contingent upon constitution, environment, and behavior. This work of trying medicines on healthy people, which Hahnemann termed “proving,” was intensely subjective. The men recruited to systematically imbibe and record were called “provers,” and Hahnemann chose them individually from among his able-bodied colleagues with the guarantee that “All were persons capable of carrying out observations, and of absolute honesty of purpose, so that I could vouch for them, and I do.”2 Provers had to regard their own minds and bodies with scientific detachment, even as foreign substances wreaked havoc.
', author_id: User.all.sample.id, image: File.open('app/assets/images/story/shoes.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'The scenes are among the most heartless in cinema history: a drunken, abusive showman exhibiting the severely deformed Joseph Merrick to horrified punters. David Lynch’s The Elephant Man begins with its lead character being treated little better than an animal in a cage. But it soon finds a clean-cut hero in the ambitious young surgeon Frederick Treves, who rescues the hapless Merrick from his keeper and gives him permanent shelter at the London Hospital. Supported by charitable donations, the victim recovers his humanity: he learns to speak again (in a decidedly middle-class accent), to entertain society guests and to dress and behave like a well-heeled young dandy. Merrick, no more the degraded show freak, reveals his inner goodness and spirituality and dies happy.

Lynch’s movie is based largely on Treves’ sentimental chronicle. But that narrative is merely one version of events – and one that in the end tells us more about middle-class morality than it does about Merrick. There is another story that casts a different light on what happened. The memoirs of Tom Norman, Merrick’s London manager, are surely as biased as Treves’. But as one of the most respected showmen of his day, Norman’s account challenges head on Treves’ claim that Merrick was ultimately better off in the hospital than at the freakshow.

In August 1884, after checking himself out of the Leicester workhouse, Merrick began his career as “the Elephant Man”. The exhibition of human oddities had been part of English entertainment since at least the Elizabethan period. In the 1880s, alongside the Elephant Man, the British public could see Jo-Jo the Dog-Faced Boy, American Jack the Frog Man, Krao the Missing Link, Herr Unthan the Armless Wonder and any number of giants, dwarfs, bearded women and other “freaks of nature”. Despite the freakshow’s popularity, by the end of the 19th century, middle-class morality was condemning it as immoral, indecent and exploitive.
', author_id: User.all.sample.id, image: File.open('app/assets/images/story/spencer.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'The Greek-speaking rhetorician and writer Lucian of Samosata, born around 125 CE in what is now known as Syria, has had a somewhat mixed reception through the ages. Scholars agree that his contemporaries and successors viewed him with a great deal of respect. Early Christians were less admiring of Lucian and his pagan and vitriolic pen, though by the time of the renaissance, he had regained favor among learned people. Italian humanists translated him from Greek, and thus Lucian went on to influence the post-renaissance modern world.

While scholars divide themselves over whether Lucian’s greatest contribution lies in his preservation of classical rhetoric or his innovative force as a satirist, in either case what continues to interest casual readers and scholars alike is his profound sense of humor in investigating what are serious philosophical subjects: the moral life, epistemology, and politics. It is perhaps epistemology which can be seen as Lucian’s main focus of satire in what has become his best known work, Vera Historia (in English, True Story), a detailed and elaborate fantasy about travelling to the moon.

The Vera Historia is not only the first detailed narrative about traveling through space to the moon in the Western tradition, it is also, arguably, the strangest. On Lucian’s lunar surface we encounter a dizzying litany of bizarre beasts: three headed vultures, grass-bodied birds with wings of giant leaves, elephant-sized fleas, half women half grapevine beings from whom a kiss would send one “reeling drunk”, and men who sweat milk of such quality “that cheese can actually be made from it by dripping in a little of the honey” which runs from their noses. He also gives particular attention to innovative new methods of reproduction, a necessity in a land devoid of women. On one part of the moon babies are born from men’s swollen calves, delivered dead but brought to life “by putting it in the wind with its mouth open”. A people known as the Arboreals have a different method: a man’s right genital gland is cut off, planted, and from it “grows a very large tree of flesh, resembling the emblem of Priapus”, and from its fruit of huge acorns men are ‘shelled’.
', author_id: User.find_by(name: 'guest').id, image: File.open('app/assets/images/story/stefan.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'Unlike the Brothers Grimm, who recently metamorphosed from children’s story collectors to godfathers of gore for the fairy-tale series, Grimm, Charles Perrault’s name remains generally unrecognizable. Yet, his stories, first published in 1697 as the Histoires ou Contes du temps passé (Stories or Tales of The Past) are anything but. Characters he immortalized, such as Cinderella with the glass slippers, the beauty who sleeps one hundred years, and the puss in boots, were destined for centuries of translation and revival. If he did not invent all of them — some appear in different guises in older folklore traditions — he did invent many of the particularities of their stories as we know them today.

That said, most readers no doubt know these titles in English, not French and, in that sense, are familiar not with Perrault’s stories per se, but with the healthy tradition of English translation, inaugurated in 1729. Precious little has been said about those published words — the language of the eighteenth century that turned Cendrillon into Cinderella.1 One basic reason for this oversight in scholarship no doubt comes down to a long-standing premise about the 1697 fairy tales: that they fell out of favor in the early eighteenth century and disappeared for a spell.2 According to this argument, they reemerged in the nineteenth century with the recovery tactics of publishers interested in hooking a younger audience for these tales and with the Grimms, who credited Perrault with inspiring their work.3

Yet, when one looks into the early reception of the tales in Britain, extant editions tell a different story about Perrault’s fate during the Enlightenment. Libraries such as the Toronto Library, Osborne Collection of Early Children’s Books, Princeton University’s Cotsen Chidren’s Library, the Pierpont Morgan Library, and the British Library are home to myriad eighteenth-century editions of the tales: large, small, fancy, cheap, and all of them delighted by their subject matter. Pirated French editions in Amsterdam and rapid-fire translations from London rolled off the presses every few years. Copies of copies slid down the social ladder and made their way into chapbooks. Woodcutters busily carved variations of earlier images for their publishers, leaving posterity with dozens of illustrations of stories credited to M. Perrault. If France abandoned her native son in the early years of the century, French-speaking publishers in Amsterdam and their eager British counterparts gave him a glorious afterlife.
', author_id: User.find_by(name: 'guest').id, image: File.open('app/assets/images/story/sweet.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: '
In 1655, after more than two decades of toil, Athanasius Kircher published Egyptian Oedipus. With his title, the Jesuit scholar characteristically paid honor to himself. Like Oedipus answering the riddle of the Sphinx, Kircher believed he had solved the enigma of the hieroglyphs. Together with its companion volume, Pamphilian Obelisk, Kircher’s magnum opus presented Latin translations of hieroglyphic inscriptions — utterly mistaken, as post–Rosetta-Stone Egyptology would reveal — preceded by treatises on ancient Egyptian history, the origins of idolatry, allegorical and symbolic wisdom, and numerous non-Egyptian textual traditions that supposedly preserved elements of the “hieroglyphic doctrine.” In addition to ancient Greek and Latin authors, Kircher’s vast array of sources included texts in Oriental languages, including Hebrew, Arabic, Aramaic, Coptic, Samaritan, and Ethiopian, as well as archeological evidence. The resulting amalgam is, without doubt, impressive. But it can also bewilder.

Egyptian Oedipus promised a complete “restoration of the hieroglyphic doctrine,” all the lost secrets of religion and science that ancient Egyptians supposedly encoded on their monuments. The massive final volume gathered almost every hieroglyphic inscription known to Europeans at that time, as well as other ancient artifacts, including mummies, sarcophagi, Canopic jars, sphinxes, idols, lamps, and amulets, found in Rome, other Christian cities, Istanbul, and Egypt. Kircher glossed each object with a learned explanation of its ancient significance. Without a Rosetta Stone, he translated the hieroglyphic inscriptions, character by character, into Latin prose.

But Egyptian Oedipus hardly confined itself to matters Egyptian. Kircher interpreted the hieroglyphs by comparing Egyptian inscriptions with evidence from other traditions that supposedly preserved elements of the “hieroglyphic doctrine.” The book contained extensive discussions of topics such as pagan religion from Mexico to Japan, ancient Greek esoteric texts like the Orphic hymns and Pythagorean verses, Jewish Kabbalah, Arabic magic, ancient alchemy, astrology, and astral medicine. To harmonize the “sacred history” of the Bible with the “profane history” of pagan civilizations, Kircher had recourse to symbolism and allegory. Properly interpreted, the seemingly “absurd” myths of the Greeks, Egyptians, and other heathens express a monotheistic theology that prefigures many of the tenets of Christianity. Among the many levels of meaning contained in the story of Isis and Osiris, for example, Kircher detected the doctrine of the Holy Trinity.

At the dawn of time, Kircher, explained, Adam, instructed by God and the angels, and guided by experience acquired during his centuries-spanning life, possessed perfect wisdom, which he passed on to his children. Noah and his sons preserved antediluvian knowledge from destruction by the Flood, which Kircher placed 1,656 years after the creation of the world and 2,394 years before the birth of Christ. But Noah’s son Ham polluted the Adamic wisdom with magic and superstition. Eventually the great Egyptian sage Hermes Trismegistus recovered the pure antediluvian wisdom and invented hieroglyphic writing to preserve it for posterity. But later Egyptian priests mixed the Hermetic wisdom with magic and superstition, creating, yet again, an ambiguous legacy, which was passed on to other nations.
', author_id: User.find_by(name: 'guest').id, image: File.open('app/assets/images/story/tom.jpg'))

Story.create!(title: Faker::Company.unique.catch_phrase, body: 'Andreas Vesalius threw down a glove in front of established medicine and its scholars when, in 1543, he produced a massive anatomy text titled De Humani Corporis Fabrica — on the fabric of the human body.

Vesalius believed that the field of medicine was being ill served by sending its students to books to learn their anatomy. The flesh itself had to teach, not merely the page. This idea of hands-on learning trumping an ancient textual legacy was an affront to many of Vesalius’ medical peers. Medicine was not a handicraft, but a noble scholastic art. Far from trying to disparage his discipline, Vesalius intended to elevate the most denigrated field of medicine – surgery – to that same level of esteem. He was taking a professional risk. But the Fabrica, the result of untold hours of dissection and writing, largely spoke persuasively for itself. Vesalius exposed hundreds of mistakes made by Galen, whose writings were still considered the chief source on anatomy over a thousand years after they had been written.

Naturally, there were some who still believed that Vesalius had misunderstood what he had seen in his dissections, or Galen’s explanation itself. But the stance the Fabrica and its author took gained attention, and the idea of an apprenticeship in anatomy at the slab, rather than the desk, began to gain ground.
', author_id: User.find_by(name: 'guest').id, image: File.open('app/assets/images/story/william.jpg'))
